
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://gdxaqfrodyfygurwrqwm.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkeGFxZnJvZHlmeWd1cndycXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzQxODAsImV4cCI6MjA2MjE1MDE4MH0.fp64K4QifCqyvyVqSCOlENDyixa3cBO4rpcfmFXgnYU';

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
