// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Safely resolve environment variables for Supabase configuration
const metaEnv =
  typeof import.meta !== 'undefined' && typeof import.meta.env !== 'undefined'
    ? (import.meta.env as Record<string, string | undefined>)
    : undefined;
const processEnv =
  typeof process !== 'undefined' && typeof process.env !== 'undefined'
    ? (process.env as Record<string, string | undefined>)
    : undefined;

const SUPABASE_URL =
  metaEnv?.VITE_SUPABASE_URL ||
  metaEnv?.EXPO_PUBLIC_SUPABASE_URL ||
  processEnv?.VITE_SUPABASE_URL ||
  processEnv?.EXPO_PUBLIC_SUPABASE_URL ||
  'https://bslcyuufvifphfzdgfcl.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  metaEnv?.VITE_SUPABASE_ANON_KEY ||
  metaEnv?.EXPO_PUBLIC_SUPABASE_ANON_KEY ||
  processEnv?.VITE_SUPABASE_ANON_KEY ||
  processEnv?.EXPO_PUBLIC_SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbGN5dXVmdmlmcGhmemRnZmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjkzNjYsImV4cCI6MjA2Nzk0NTM2Nn0.HzpSCytm8iu3HZa37vcqozNUNGGfDmCGiv_CMcXJ3uE';

const authStorage = typeof globalThis !== "undefined" && "localStorage" in globalThis ? globalThis.localStorage : undefined;


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
